language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install Appium-Python-Client
  
# command to run tests
script:
  - python hello.py
